#!/bin/bash

urls="$(xurls <&0 | uniq)"
# It's all one line now so count words. Not sure why but this works. Rofi
# still handles it properly.
urlcount=$(echo "$urls" | wc -w)

if [ $urlcount -eq 1 ]; then
    xdg-open "$urls"
elif [ ! $urlcount -eq 0 ]; then
    echo "$urls" | tac | dmenu -i -l $urlcount | xargs -r xdg-open 2> /dev/null
fi
